/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/0xcadams/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { ZeroCustomType } from "drizzle-zero";
import type * as drizzleSchema from "../../crud/src/db/schema";
import type { DrizzleToZeroSchema } from "drizzle-zero";

type ZeroSchema = DrizzleToZeroSchema<typeof drizzleSchema>;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "installations": {
            "name": "installations",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "installations", "id">
                },
                "createdAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "installations", "createdAt">,
                    "serverName": "created_at"
                },
                "updatedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "installations", "updatedAt">,
                    "serverName": "updated_at"
                },
                "deletedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "installations", "deletedAt">,
                    "serverName": "deleted_at"
                },
                "type": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "installations", "type">
                },
                "externalId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "installations", "externalId">,
                    "serverName": "external_id"
                },
                "externalName": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "installations", "externalName">,
                    "serverName": "external_name"
                },
                "credentials": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "installations", "credentials">
                },
                "metadata": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "installations", "metadata">
                },
                "organizationId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "installations", "organizationId">,
                    "serverName": "organization_id"
                }
            },
            "primaryKey": ["id"]
        },
        "organizationMembers": {
            "name": "organizationMembers",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizationMembers", "id">
                },
                "createdAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizationMembers", "createdAt">,
                    "serverName": "created_at"
                },
                "updatedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizationMembers", "updatedAt">,
                    "serverName": "updated_at"
                },
                "deletedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizationMembers", "deletedAt">,
                    "serverName": "deleted_at"
                },
                "role": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizationMembers", "role">
                },
                "organizationId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizationMembers", "organizationId">,
                    "serverName": "organization_id"
                },
                "userId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizationMembers", "userId">,
                    "serverName": "user_id"
                }
            },
            "primaryKey": ["id"],
            "serverName": "organization_members"
        },
        "organizations": {
            "name": "organizations",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizations", "id">
                },
                "createdAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizations", "createdAt">,
                    "serverName": "created_at"
                },
                "updatedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizations", "updatedAt">,
                    "serverName": "updated_at"
                },
                "deletedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizations", "deletedAt">,
                    "serverName": "deleted_at"
                },
                "name": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizations", "name">
                },
                "slug": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizations", "slug">
                },
                "completedOnboarding": {
                    "type": "boolean",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "organizations", "completedOnboarding">,
                    "serverName": "completed_onboarding"
                }
            },
            "primaryKey": ["id"]
        },
        "tags": {
            "name": "tags",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "tags", "id">
                },
                "createdAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "tags", "createdAt">,
                    "serverName": "created_at"
                },
                "updatedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "tags", "updatedAt">,
                    "serverName": "updated_at"
                },
                "deletedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "tags", "deletedAt">,
                    "serverName": "deleted_at"
                },
                "name": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "tags", "name">
                },
                "color": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "tags", "color">
                },
                "organizationId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "tags", "organizationId">,
                    "serverName": "organization_id"
                }
            },
            "primaryKey": ["id"]
        },
        "todoTags": {
            "name": "todoTags",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todoTags", "id">
                },
                "createdAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todoTags", "createdAt">,
                    "serverName": "created_at"
                },
                "todoId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todoTags", "todoId">,
                    "serverName": "todo_id"
                },
                "tagId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todoTags", "tagId">,
                    "serverName": "tag_id"
                }
            },
            "primaryKey": ["id"],
            "serverName": "todo_tags"
        },
        "todos": {
            "name": "todos",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "id">
                },
                "createdAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "createdAt">,
                    "serverName": "created_at"
                },
                "updatedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "updatedAt">,
                    "serverName": "updated_at"
                },
                "deletedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "deletedAt">,
                    "serverName": "deleted_at"
                },
                "title": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "title">
                },
                "description": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "description">
                },
                "completed": {
                    "type": "boolean",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "completed">
                },
                "dueDate": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "dueDate">,
                    "serverName": "due_date"
                },
                "priority": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "priority">
                },
                "status": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "status">
                },
                "userId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "userId">,
                    "serverName": "user_id"
                },
                "organizationId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "organizationId">,
                    "serverName": "organization_id"
                },
                "version": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "version">
                },
                "lastEditedBy": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "lastEditedBy">,
                    "serverName": "last_edited_by"
                },
                "lastEditedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "todos", "lastEditedAt">,
                    "serverName": "last_edited_at"
                }
            },
            "primaryKey": ["id"]
        },
        "userInvitations": {
            "name": "userInvitations",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "userInvitations", "id">
                },
                "createdAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "userInvitations", "createdAt">,
                    "serverName": "created_at"
                },
                "updatedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "userInvitations", "updatedAt">,
                    "serverName": "updated_at"
                },
                "deletedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "userInvitations", "deletedAt">,
                    "serverName": "deleted_at"
                },
                "createdById": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "userInvitations", "createdById">,
                    "serverName": "created_by_id"
                },
                "email": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "userInvitations", "email">
                },
                "role": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "userInvitations", "role">
                },
                "organizationId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "userInvitations", "organizationId">,
                    "serverName": "organization_id"
                }
            },
            "primaryKey": ["id"],
            "serverName": "user_invitations"
        },
        "users": {
            "name": "users",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "users", "id">
                },
                "createdAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "users", "createdAt">,
                    "serverName": "created_at"
                },
                "updatedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "users", "updatedAt">,
                    "serverName": "updated_at"
                },
                "deletedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "users", "deletedAt">,
                    "serverName": "deleted_at"
                },
                "name": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "users", "name">
                },
                "email": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "users", "email">
                },
                "avatarUrl": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<ZeroSchema, "users", "avatarUrl">,
                    "serverName": "avatar_url"
                }
            },
            "primaryKey": ["id"]
        }
    },
    "relationships": {
        "installations": {
            "organization": [{ "sourceField": ["organizationId"], "destField": ["id"], "destSchema": "organizations", "cardinality": "one" }]
        },
        "organizationMembers": {
            "organization": [{ "sourceField": ["organizationId"], "destField": ["id"], "destSchema": "organizations", "cardinality": "one" }],
            "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }]
        },
        "organizations": {
            "members": [{ "sourceField": ["id"], "destField": ["organizationId"], "destSchema": "organizationMembers", "cardinality": "many" }],
            "invitations": [{ "sourceField": ["id"], "destField": ["organizationId"], "destSchema": "userInvitations", "cardinality": "many" }]
        },
        "tags": {
            "organization": [{ "sourceField": ["organizationId"], "destField": ["id"], "destSchema": "organizations", "cardinality": "one" }],
            "todoTags": [{ "sourceField": ["id"], "destField": ["tagId"], "destSchema": "todoTags", "cardinality": "many" }]
        },
        "todoTags": {
            "todo": [{ "sourceField": ["todoId"], "destField": ["id"], "destSchema": "todos", "cardinality": "one" }],
            "tag": [{ "sourceField": ["tagId"], "destField": ["id"], "destSchema": "tags", "cardinality": "one" }]
        },
        "todos": {
            "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }],
            "organization": [{ "sourceField": ["organizationId"], "destField": ["id"], "destSchema": "organizations", "cardinality": "one" }],
            "lastEditedByUser": [{ "sourceField": ["lastEditedBy"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }],
            "todoTags": [{ "sourceField": ["id"], "destField": ["todoId"], "destSchema": "todoTags", "cardinality": "many" }]
        },
        "userInvitations": {
            "createdBy": [{ "sourceField": ["createdById"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }],
            "organization": [{ "sourceField": ["organizationId"], "destField": ["id"], "destSchema": "organizations", "cardinality": "one" }]
        },
        "users": {
            "memberships": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "organizationMembers", "cardinality": "many" }]
        }
    }
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
