# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b60d764a95fd19dfc2f4c1c2e68b458b"
name = "superscale-test-app"
handle = "superscale-test-app"
application_url = "https://boar-helped-mite.ngrok-free.app/api/auth/shopify"
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "quickstart-5d36455a.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://boar-helped-mite.ngrok-free.app/api/auth/shopify/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
