packages:
  - apps/*
  - packages/*

catalog:
  "@supabase/supabase-js": 2.54.0
  "@tanstack/react-query": ^5.84.0
  "@types/node": ^22.14.1
  "@types/react": ^19.0.2
  "@types/react-dom": ^19.0.2
  "@rocicorp/zero": ^0.22.2025080200
  autoprefixer: 10.4.14
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  date-fns: ^2.30.0
  dotenv: ^16.4.7
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.38.3
  next: 15.4.5
  postcss: 8.4.49
  react: 19.1.1
  react-dom: 19.1.1
  react-hook-form: ^7.62.0
  tailwind-merge: ^3.3.1
  tailwindcss: 4.0.0
  tsx: ^4.19.2
  typescript: 5.9.2
  vitest: ^2.1.8
  zod: ^3.24.1
